//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film_Staff()
        {
            this.Staff_in_film = new HashSet<Staff_in_film>();
        }
    
        public long person_id { get; set; }
        public string name { get; set; }
        public string birthPlace { get; set; }
        public System.DateTime birthday { get; set; }
        public string sex { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_in_film> Staff_in_film { get; set; }
    }
}
