//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_in_film
    {
        public long person_id { get; set; }
        public long film_id { get; set; }
        public string role_name { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Film_Staff Film_Staff { get; set; }
        public virtual Role Role { get; set; }
    }
}
